from setuptools import setup, find_packages

setup(
    name            = 'tradeschool',
    version         = '1.0',
    description     ='Trade school everywhere',
    author          ='or zubalsky',
    author_email    ='orzubalsky@gmail.com',
    package_dir     = {'': 'ts/apps/tradeschool'},
    packages        = find_packages('ts/apps/tradeschool'),
    install_requires = [
        'MySQL-python==1.2.3',
        'PIL',
        'django==1.5.1',
        'django-admin-enhancer',
        'django-countries',
        'django-dajaxice',
        'django-debug-toolbar',
        'django-flatpages-tinymce',
        'django-grappelli',
        'django-guardian',
        'django-mailer',
        'django-rosetta',
        'django-rosetta-grappelli',
        'django-tastypie',
        'django-templatesadmin',
        'django-tinymce',
        'django_ace',
        'docutils',
        'feedparser',
        'johnny-cache',
        'polib',
        'python-memcached',
        'pytz',
        'requests',
        'selenium',
        'simplejson',
        'six',
        'south',
    ],
)
